"""
Data flow contract tests — verifies that producers and consumers of key data
structures (test_intentions, dependency_map, gates) agree on location, field
names, and semantics.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from conftest import FRAMEWORK_ROOT, read_text

# ── Helpers ──────────────────────────────────────────────────────────────


def _mentions(content: str, *terms: str) -> bool:
    """Check if content mentions ALL given terms (case-insensitive)."""
    lower = content.lower()
    return all(t.lower() in lower for t in terms)


# ── test_intentions data flow ────────────────────────────────────────────


class TestTestIntentionsDataFlow:
    """
    test_intentions are written by the refinement agent into specs/stories/[feature-id].yaml.
    They must be READ from that same location by:
    - test-engineer.md (writes tests from intentions)
    - builder-service.md (reads intentions for coverage)
    - builder-frontend.md (reads intentions for coverage)
    - check_test_intentions.py (enforces coverage)
    - build/SKILL.md (documents the pipeline)

    They must NOT be expected in _work/spec/ (spec overlay).
    """

    # Where test_intentions are WRITTEN
    def test_story_template_has_test_intentions(self):
        template = read_text(FRAMEWORK_ROOT / "specs" / "templates" / "story-template.yaml")
        assert "test_intentions:" in template, (
            "story-template.yaml must define test_intentions section"
        )

    def test_spec_overlay_template_has_no_test_intentions(self):
        overlay = FRAMEWORK_ROOT / "specs" / "templates" / "spec-overlay-template.yaml"
        if overlay.exists():
            content = read_text(overlay)
            assert "test_intentions:" not in content, (
                "spec-overlay-template.yaml must NOT contain test_intentions "
                "(they belong in the story file)"
            )

    # Where test_intentions are READ
    def test_test_engineer_reads_from_story_file(self):
        content = read_text(FRAMEWORK_ROOT / "agents" / "test-engineer.md")
        assert _mentions(content, "test_intentions", "specs/stories/"), (
            "test-engineer.md must read test_intentions from specs/stories/ (story file)"
        )

    def test_builder_service_reads_from_story_file(self):
        content = read_text(FRAMEWORK_ROOT / "agents" / "builder-service.md")
        assert _mentions(content, "test_intentions", "specs/stories/"), (
            "builder-service.md must read test_intentions from specs/stories/ (story file)"
        )

    def test_builder_frontend_reads_from_story_file(self):
        content = read_text(FRAMEWORK_ROOT / "agents" / "builder-frontend.md")
        assert _mentions(content, "test_intentions", "specs/stories/"), (
            "builder-frontend.md must read test_intentions from specs/stories/ (story file)"
        )

    def test_check_test_intentions_searches_story_files(self):
        """The enforcement script must search specs/stories/ for test_intentions."""
        content = read_text(FRAMEWORK_ROOT / "scripts" / "check_test_intentions.py")
        assert "specs" in content and "stories" in content, (
            "check_test_intentions.py must search specs/stories/ for test_intentions"
        )

    def test_spec_overlay_input_says_not_test_intentions(self):
        """Agents that list _work/spec/ as Input must clarify it has NO test_intentions."""
        agents_with_spec_overlay = [
            "test-engineer.md",
            "builder-service.md",
            "builder-frontend.md",
        ]
        violations: list[str] = []
        for agent_name in agents_with_spec_overlay:
            content = read_text(FRAMEWORK_ROOT / "agents" / agent_name)
            # Check that the spec overlay line mentions "NOT test_intentions"
            if "_work/spec/" in content and "NOT test_intentions" not in content:
                violations.append(agent_name)
        assert not violations, (
            f"These agents reference _work/spec/ without clarifying 'NOT test_intentions': "
            f"{violations}"
        )


# ── dependency_map data flow ─────────────────────────────────────────────


class TestDependencyMapDataFlow:
    """
    dependency_map is generated by /build orchestrator and consumed by:
    - test-engineer.md (uses touched_functions, existing_tests, connected_components)
    - build/SKILL.md (documents generation procedure)
    - build-template.yaml (defines the schema)
    """

    DEPENDENCY_MAP_FIELDS = ["touched_functions", "existing_tests", "connected_components"]

    def test_build_template_has_dependency_map(self):
        template = read_text(FRAMEWORK_ROOT / "specs" / "templates" / "build-template.yaml")
        assert "dependency_map:" in template, "build-template.yaml must define dependency_map"

    def test_build_template_has_all_fields(self):
        template = read_text(FRAMEWORK_ROOT / "specs" / "templates" / "build-template.yaml")
        for field in self.DEPENDENCY_MAP_FIELDS:
            assert field in template, (
                f"build-template.yaml dependency_map missing field: {field}"
            )

    def test_build_skill_documents_generation(self):
        skill = read_text(FRAMEWORK_ROOT / "skills" / "build" / "SKILL.md")
        assert _mentions(skill, "dependency_map", "dependency map"), (
            "build/SKILL.md must document dependency map generation"
        )

    def test_test_engineer_consumes_dependency_map(self):
        content = read_text(FRAMEWORK_ROOT / "agents" / "test-engineer.md")
        assert "dependency_map" in content, (
            "test-engineer.md must reference dependency_map"
        )
        for field in self.DEPENDENCY_MAP_FIELDS:
            assert field in content, (
                f"test-engineer.md must reference dependency_map.{field}"
            )

    def test_builders_check_connected_components(self):
        """Builders that modify files should check connected_components."""
        builders = ["builder-service.md", "builder-frontend.md"]
        for builder in builders:
            content = read_text(FRAMEWORK_ROOT / "agents" / builder)
            assert "connected_components" in content or "dependency_map" in content, (
                f"{builder} must check dependency_map (connected_components) before modifying files"
            )


# ── Gates data flow ──────────────────────────────────────────────────────


class TestGatesDataFlow:
    """
    Build template gates must match the gates described in SKILL.md and CLAUDE.md.
    """

    BUILD_TEMPLATE_GATES = [
        "tdd_red",
        "tdd_green",
        "code_review",
        "security_audit",
        "sonarqube",
        "story_review",
        "validation",
    ]

    def test_build_template_has_all_gates(self):
        template = read_text(FRAMEWORK_ROOT / "specs" / "templates" / "build-template.yaml")
        for gate in self.BUILD_TEMPLATE_GATES:
            assert gate in template, f"build-template.yaml missing gate: {gate}"

    def test_build_template_gates_have_status_field(self):
        template = read_text(FRAMEWORK_ROOT / "specs" / "templates" / "build-template.yaml")
        # Each gate section should have a status: field
        gate_count = template.count("status: pending")
        # validation also has status
        assert gate_count >= len(self.BUILD_TEMPLATE_GATES), (
            f"Expected at least {len(self.BUILD_TEMPLATE_GATES)} gates with 'status: pending', "
            f"found {gate_count}"
        )

    def test_skill_md_documents_seven_gates(self):
        """SKILL.md must document 7 sequential validation gates."""
        skill = read_text(FRAMEWORK_ROOT / "skills" / "build" / "SKILL.md")
        # Count "Gate N" patterns
        gate_refs = re.findall(r"\*\*Gate\s+(\d+)", skill)
        gate_numbers = sorted(set(int(g) for g in gate_refs))
        assert gate_numbers == [1, 2, 3, 4, 5, 6, 7], (
            f"SKILL.md should document Gates 1-7, found: {gate_numbers}"
        )

    def test_claudemd_documents_seven_gates(self):
        """CLAUDE.md phase workflow must mention all 7 gates."""
        claude_md = read_text(FRAMEWORK_ROOT / "rules" / "CLAUDE.md")
        # Check that gates are mentioned in the phase workflow
        for i in range(1, 8):
            assert f"Gate {i}" in claude_md, (
                f"rules/CLAUDE.md missing Gate {i} in phase workflow"
            )

    def test_sonarqube_gate_is_optional(self):
        """SonarQube gate must be documented as skippable."""
        skill = read_text(FRAMEWORK_ROOT / "skills" / "build" / "SKILL.md")
        # Should mention "skipped" for SonarQube
        sonar_section = ""
        for line in skill.splitlines():
            if "sonarqube" in line.lower() or "gate 6" in line.lower():
                sonar_section += line + "\n"
        assert "skip" in sonar_section.lower(), (
            "SonarQube gate must be documented as optional/skippable"
        )

    def test_story_review_gate_is_mandatory(self):
        """Story review (Gate 7) must be documented as mandatory."""
        skill = read_text(FRAMEWORK_ROOT / "skills" / "build" / "SKILL.md")
        assert "mandatory" in skill.lower() and "story" in skill.lower(), (
            "Story review gate must be documented as mandatory"
        )


# ── AC verify: data flow ────────────────────────────────────────────────


class TestACVerifyDataFlow:
    """
    verify: fields flow from story template → story file → validator execution.
    """

    def test_story_template_has_verify_field(self):
        template = read_text(FRAMEWORK_ROOT / "specs" / "templates" / "story-template.yaml")
        assert 'verify:' in template, "story-template.yaml must define verify: field in ACs"

    def test_story_template_bans_verify_static(self):
        template = read_text(FRAMEWORK_ROOT / "specs" / "templates" / "story-template.yaml")
        assert "static" in template.lower() and "banned" in template.lower(), (
            "story-template.yaml must document that 'verify: static' is BANNED"
        )

    def test_build_skill_checks_verify_fields(self):
        """Build SKILL.md prerequisites must verify all ACs have verify: field."""
        skill = read_text(FRAMEWORK_ROOT / "skills" / "build" / "SKILL.md")
        assert _mentions(skill, "verify:", "AC"), (
            "Build SKILL.md prerequisites must check that all ACs have verify: field"
        )
