"""
Data flow contract tests — verifies that producers and consumers of key data
structures (test_intentions, dependency_map, gates, wireframes, validation ACs)
agree on location, field names, and semantics.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from conftest import FRAMEWORK_ROOT, read_text

# ── Helpers ──────────────────────────────────────────────────────────────


def _mentions(content: str, *terms: str) -> bool:
    """Check if content mentions ALL given terms (case-insensitive)."""
    lower = content.lower()
    return all(t.lower() in lower for t in terms)


# ── test_intentions data flow ────────────────────────────────────────────


class TestTestIntentionsDataFlow:
    """
    test_intentions are written by the refinement agent into specs/stories/[feature-id].yaml.
    They must be READ from that same location by:
    - test-engineer.md (writes tests from intentions)
    - builder-service.md (reads intentions for coverage)
    - builder-frontend.md (reads intentions for coverage)
    - check_test_intentions.py (enforces coverage)
    - build/SKILL.md (documents the pipeline)

    They must NOT be expected in _work/spec/ (spec overlay).
    """

    # Where test_intentions are WRITTEN
    def test_story_template_has_test_intentions(self):
        template = read_text(FRAMEWORK_ROOT / "specs" / "templates" / "story-template.yaml")
        assert "test_intentions:" in template, (
            "story-template.yaml must define test_intentions section"
        )

    def test_spec_overlay_template_has_no_test_intentions(self):
        overlay = FRAMEWORK_ROOT / "specs" / "templates" / "spec-overlay-template.yaml"
        if overlay.exists():
            content = read_text(overlay)
            assert "test_intentions:" not in content, (
                "spec-overlay-template.yaml must NOT contain test_intentions "
                "(they belong in the story file)"
            )

    # Where test_intentions are READ
    def test_test_engineer_reads_from_story_file(self):
        content = read_text(FRAMEWORK_ROOT / "agents" / "test-engineer.md")
        assert _mentions(content, "test_intentions", "specs/stories/"), (
            "test-engineer.md must read test_intentions from specs/stories/ (story file)"
        )

    def test_builder_service_reads_from_story_file(self):
        content = read_text(FRAMEWORK_ROOT / "agents" / "builder-service.md")
        assert _mentions(content, "test_intentions", "specs/stories/"), (
            "builder-service.md must read test_intentions from specs/stories/ (story file)"
        )

    def test_builder_frontend_reads_from_story_file(self):
        content = read_text(FRAMEWORK_ROOT / "agents" / "builder-frontend.md")
        assert _mentions(content, "test_intentions", "specs/stories/"), (
            "builder-frontend.md must read test_intentions from specs/stories/ (story file)"
        )

    def test_check_test_intentions_searches_story_files(self):
        """The enforcement script must search specs/stories/ for test_intentions."""
        content = read_text(FRAMEWORK_ROOT / "scripts" / "check_test_intentions.py")
        assert "specs" in content and "stories" in content, (
            "check_test_intentions.py must search specs/stories/ for test_intentions"
        )

    def test_spec_overlay_input_says_not_test_intentions(self):
        """Agents that list _work/spec/ as Input must clarify it has NO test_intentions."""
        agents_with_spec_overlay = [
            "test-engineer.md",
            "builder-service.md",
            "builder-frontend.md",
        ]
        violations: list[str] = []
        for agent_name in agents_with_spec_overlay:
            content = read_text(FRAMEWORK_ROOT / "agents" / agent_name)
            # Check that the spec overlay line mentions "NOT test_intentions"
            if "_work/spec/" in content and "NOT test_intentions" not in content:
                violations.append(agent_name)
        assert not violations, (
            f"These agents reference _work/spec/ without clarifying 'NOT test_intentions': "
            f"{violations}"
        )


# ── dependency_map data flow ─────────────────────────────────────────────


class TestDependencyMapDataFlow:
    """
    dependency_map is generated by /build orchestrator and consumed by:
    - test-engineer.md (uses touched_functions, existing_tests, connected_components)
    - build/SKILL.md (documents generation procedure)
    - build-template.yaml (defines the schema)
    """

    DEPENDENCY_MAP_FIELDS = ["touched_functions", "existing_tests", "connected_components"]

    def test_build_template_has_dependency_map(self):
        template = read_text(FRAMEWORK_ROOT / "specs" / "templates" / "build-template.yaml")
        assert "dependency_map:" in template, "build-template.yaml must define dependency_map"

    def test_build_template_has_all_fields(self):
        template = read_text(FRAMEWORK_ROOT / "specs" / "templates" / "build-template.yaml")
        for field in self.DEPENDENCY_MAP_FIELDS:
            assert field in template, (
                f"build-template.yaml dependency_map missing field: {field}"
            )

    def test_build_skill_documents_generation(self):
        skill = read_text(FRAMEWORK_ROOT / "skills" / "build" / "SKILL.md")
        assert _mentions(skill, "dependency_map", "dependency map"), (
            "build/SKILL.md must document dependency map generation"
        )

    def test_test_engineer_consumes_dependency_map(self):
        content = read_text(FRAMEWORK_ROOT / "agents" / "test-engineer.md")
        assert "dependency_map" in content, (
            "test-engineer.md must reference dependency_map"
        )
        for field in self.DEPENDENCY_MAP_FIELDS:
            assert field in content, (
                f"test-engineer.md must reference dependency_map.{field}"
            )

    def test_builders_check_connected_components(self):
        """Builders that modify files should check connected_components."""
        builders = ["builder-service.md", "builder-frontend.md"]
        for builder in builders:
            content = read_text(FRAMEWORK_ROOT / "agents" / builder)
            assert "connected_components" in content or "dependency_map" in content, (
                f"{builder} must check dependency_map (connected_components) before modifying files"
            )


# ── Gates data flow ──────────────────────────────────────────────────────


class TestGatesDataFlow:
    """
    Build template gates must match the 11 gates described in SKILL.md and CLAUDE.md.
    """

    BUILD_TEMPLATE_GATES = [
        "security",
        "unit_tests",
        "code_quality",
        "e2e_code",
        "wcag_wireframes",
        "e2e_execution",
        "e2e_wireframe_validation",
        "ac_validation",
        "story_review",
        "code_review",
        "final_compilation",
    ]

    BUILD_TEMPLATE_PHASES = [
        "red_phase",
        "green_phase",
    ]

    def test_build_template_has_all_gates(self):
        template = read_text(FRAMEWORK_ROOT / "specs" / "templates" / "build-template.yaml")
        for gate in self.BUILD_TEMPLATE_GATES:
            assert gate in template, f"build-template.yaml missing gate: {gate}"

    def test_build_template_has_red_green_phases(self):
        template = read_text(FRAMEWORK_ROOT / "specs" / "templates" / "build-template.yaml")
        for phase in self.BUILD_TEMPLATE_PHASES:
            assert phase in template, f"build-template.yaml missing phase: {phase}"

    def test_build_template_gates_have_status_field(self):
        template = read_text(FRAMEWORK_ROOT / "specs" / "templates" / "build-template.yaml")
        gate_count = template.count("status: pending")
        # 11 gates + red_phase (3 sub-statuses) + green_phase (2 sub-statuses) + top-level statuses
        assert gate_count >= len(self.BUILD_TEMPLATE_GATES), (
            f"Expected at least {len(self.BUILD_TEMPLATE_GATES)} gates with 'status: pending', "
            f"found {gate_count}"
        )

    def test_skill_md_documents_eleven_gates(self):
        """SKILL.md must document 11 sequential validation gates."""
        skill = read_text(FRAMEWORK_ROOT / "skills" / "build" / "SKILL.md")
        gate_refs = re.findall(r"\*\*Gate\s+(\d+)", skill)
        gate_numbers = sorted(set(int(g) for g in gate_refs))
        assert gate_numbers == list(range(1, 12)), (
            f"SKILL.md should document Gates 1-11, found: {gate_numbers}"
        )

    def test_claudemd_documents_eleven_gates(self):
        """CLAUDE.md phase workflow must mention all 11 gates."""
        claude_md = read_text(FRAMEWORK_ROOT / "rules" / "CLAUDE.md")
        for i in range(1, 12):
            assert f"Gate {i}" in claude_md or f"Gate  {i}" in claude_md, (
                f"rules/CLAUDE.md missing Gate {i} in phase workflow"
            )

    def test_code_quality_gate_never_skipped(self):
        """Code quality gate (Gate 3) must be documented as NEVER skipped."""
        skill = read_text(FRAMEWORK_ROOT / "skills" / "build" / "SKILL.md")
        assert "never skip" in skill.lower() or "never skipped" in skill.lower(), (
            "Code quality gate must be documented as NEVER skipped"
        )

    def test_story_review_gate_is_mandatory(self):
        """Story review (Gate 9) must be documented as mandatory."""
        skill = read_text(FRAMEWORK_ROOT / "skills" / "build" / "SKILL.md")
        assert "mandatory" in skill.lower() and "story" in skill.lower(), (
            "Story review gate must be documented as mandatory"
        )

    def test_ui_gates_skippable(self):
        """Gates 4-7 must be skippable for non-UI projects."""
        template = read_text(FRAMEWORK_ROOT / "specs" / "templates" / "build-template.yaml")
        ui_gates = ["e2e_code", "wcag_wireframes", "e2e_execution", "e2e_wireframe_validation"]
        for gate in ui_gates:
            # Must have 'skipped' as a possible status value
            assert "skipped" in template, (
                f"build-template.yaml must allow 'skipped' status for UI-only gate: {gate}"
            )


# ── Wireframe HTML data flow ────────────────────────────────────────────


class TestWireframeDataFlow:
    """
    Wireframe HTML files flow from /refine → _work/ux/wireframes/ → /build (Gates 4-7).
    """

    def test_refine_skill_documents_wireframe_gate(self):
        skill = read_text(FRAMEWORK_ROOT / "skills" / "refine" / "SKILL.md")
        assert _mentions(skill, "wireframe", "html"), (
            "refine/SKILL.md must document wireframe HTML gate"
        )

    def test_refine_skill_stores_wireframes_in_work(self):
        skill = read_text(FRAMEWORK_ROOT / "skills" / "refine" / "SKILL.md")
        assert "_work/ux/wireframes/" in skill, (
            "refine/SKILL.md must store wireframes in _work/ux/wireframes/"
        )

    def test_build_skill_references_wireframes(self):
        skill = read_text(FRAMEWORK_ROOT / "skills" / "build" / "SKILL.md")
        assert "wireframe" in skill.lower(), (
            "build/SKILL.md must reference wireframes for UI gates"
        )

    def test_build_skill_references_data_testid(self):
        skill = read_text(FRAMEWORK_ROOT / "skills" / "build" / "SKILL.md")
        assert "data-testid" in skill, (
            "build/SKILL.md must reference data-testid from wireframes"
        )

    def test_refinement_agent_documents_wireframe_workflow(self):
        content = read_text(FRAMEWORK_ROOT / "agents" / "refinement.md")
        assert _mentions(content, "wireframe", "html"), (
            "refinement.md must document wireframe HTML workflow"
        )

    def test_ux_ui_agent_produces_html_wireframes(self):
        content = read_text(FRAMEWORK_ROOT / "agents" / "ux-ui.md")
        assert _mentions(content, "html", "wireframe", "data-testid"), (
            "ux-ui.md must document HTML wireframe output with data-testid"
        )

    def test_validator_agent_references_wireframes(self):
        content = read_text(FRAMEWORK_ROOT / "agents" / "validator.md")
        assert "wireframe" in content.lower(), (
            "validator.md must reference wireframes for UI gates"
        )

    def test_story_template_has_ux_ref(self):
        template = read_text(FRAMEWORK_ROOT / "specs" / "templates" / "story-template.yaml")
        assert "ux_ref:" in template, (
            "story-template.yaml must have ux_ref: field for wireframe reference"
        )


# ── Validation ACs data flow ──────────────────────────────────────────────


class TestValidationACsDataFlow:
    """
    Auto-generated validation ACs (COMPILE, TU, CONSOLE) must be in the story template
    and documented in refine SKILL.md.
    """

    VALIDATION_AC_IDS = [
        "AC-BP-[FEATURE]-COMPILE",
        "AC-BP-[FEATURE]-TU",
        "AC-BP-[FEATURE]-CONSOLE",
    ]

    def test_story_template_has_validation_acs(self):
        template = read_text(FRAMEWORK_ROOT / "specs" / "templates" / "story-template.yaml")
        assert "validation_acs:" in template, (
            "story-template.yaml must have validation_acs section"
        )

    def test_story_template_has_compile_ac(self):
        template = read_text(FRAMEWORK_ROOT / "specs" / "templates" / "story-template.yaml")
        assert "COMPILE" in template, (
            "story-template.yaml must have AC-BP-[FEATURE]-COMPILE in validation_acs"
        )

    def test_story_template_has_tu_ac(self):
        template = read_text(FRAMEWORK_ROOT / "specs" / "templates" / "story-template.yaml")
        assert "-TU" in template, (
            "story-template.yaml must have AC-BP-[FEATURE]-TU in validation_acs"
        )

    def test_story_template_has_console_ac(self):
        template = read_text(FRAMEWORK_ROOT / "specs" / "templates" / "story-template.yaml")
        assert "CONSOLE" in template, (
            "story-template.yaml must have AC-BP-[FEATURE]-CONSOLE in validation_acs"
        )

    def test_refine_skill_documents_validation_acs(self):
        skill = read_text(FRAMEWORK_ROOT / "skills" / "refine" / "SKILL.md")
        assert _mentions(skill, "validation", "AC-BP"), (
            "refine/SKILL.md must document auto-generated validation ACs"
        )

    def test_refinement_agent_documents_validation_acs(self):
        content = read_text(FRAMEWORK_ROOT / "agents" / "refinement.md")
        assert "validation" in content.lower() and "AC-BP" in content, (
            "refinement.md must document auto-generated validation ACs"
        )


# ── AC verify: data flow ────────────────────────────────────────────────


class TestACVerifyDataFlow:
    """
    verify: fields flow from story template → story file → validator execution.
    """

    def test_story_template_has_verify_field(self):
        template = read_text(FRAMEWORK_ROOT / "specs" / "templates" / "story-template.yaml")
        assert 'verify:' in template, "story-template.yaml must define verify: field in ACs"

    def test_story_template_bans_verify_static(self):
        template = read_text(FRAMEWORK_ROOT / "specs" / "templates" / "story-template.yaml")
        assert "static" in template.lower() and "banned" in template.lower(), (
            "story-template.yaml must document that 'verify: static' is BANNED"
        )

    def test_build_skill_checks_verify_fields(self):
        """Build SKILL.md prerequisites must verify all ACs have verify: field."""
        skill = read_text(FRAMEWORK_ROOT / "skills" / "build" / "SKILL.md")
        assert _mentions(skill, "verify:", "AC"), (
            "Build SKILL.md prerequisites must check that all ACs have verify: field"
        )
